name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nebulex_test:
    name: >-
      Nebulex Test (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }} /
      OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - elixir: 1.20.x
            otp: 29.x
            os: 'ubuntu-latest'
            lint: true
            coverage: true
            sobelow: true
            dialyzer: true
            docs: true
          - elixir: 1.19.x
            otp: 28.x
            os: 'ubuntu-latest'
          - elixir: 1.18.x
            otp: 27.x
            os: 'ubuntu-latest'
          - elixir: 1.17.x
            otp: 25.x
            os: 'ubuntu-latest'
          - elixir: 1.14.x
            otp: 24.x
            os: 'ubuntu-latest'

    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '${{ matrix.otp }}'
          elixir-version: '${{ matrix.elixir }}'

      - name: Cache deps
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          key: >-
            ${{ matrix.elixir }}-${{ matrix.otp }}-${{ runner.os }}-mix-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ matrix.elixir }}-${{ matrix.otp }}-${{ runner.os }}-mix-

      - name: Cache _build
        uses: actions/cache@v4
        with:
          path: _build
          key: >-
            ${{ matrix.elixir }}-${{ matrix.otp }}-${{ runner.os }}-build-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ matrix.elixir }}-${{ matrix.otp }}-${{ runner.os }}-build-

      - name: Install Hex and Rebar
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install Dependencies
        run: mix deps.get
        if: ${{ steps.mix-cache.outputs.cache-hit != 'true' }}

      - name: Compile deps
        run: mix deps.compile

      - name: Check unused dependencies
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Audit dependencies for security advisories
        run: mix deps.audit
        if: ${{ matrix.lint }}

      - name: Compile lint
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run style and code consistency checks
        run: |
          mix format --check-formatted
          mix credo --strict
        if: ${{ matrix.lint }}

      - name: Run tests
        run: mix test
        if: ${{ !matrix.coverage }}

      - name: Run tests with coverage
        run: mix coveralls.json
        if: ${{ matrix.coverage }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          flags: unittests-elixir-${{ matrix.elixir }}-otp-${{ matrix.otp }}
        if: ${{ matrix.coverage }}

      - name: Run sobelow
        run: mix sobelow --skip --exit Low
        if: ${{ matrix.sobelow }}

      - name: Restore PLT Cache
        uses: actions/cache@v4
        id: plt-cache
        with:
          path: priv/plts
          key: >-
            plt-${{ matrix.elixir }}-${{ matrix.otp }}-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            plt-${{ matrix.elixir }}-${{ matrix.otp }}-
        if: ${{ matrix.dialyzer }}

      - name: Create PLTs
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt
        if: ${{ matrix.dialyzer && steps.plt-cache.outputs.cache-hit != 'true' }}

      - name: Run dialyzer
        run: mix dialyzer --format github
        if: ${{ matrix.dialyzer }}

      - name: Run documentation health check
        run: mix doctor
        if: ${{ matrix.docs }}
